=== UnitasBrooks/bespoke/src/bespoke/xsd/global_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!--SIMPLE TYPES-->
  <!--The path can be followed by a backslash.-->
  <xs:simpleType name="validPath">
    <xs:restriction base="xs:normalizedString">
      <xs:minLength value="1"/>
      <xs:maxLength value="260"/>
    </xs:restriction>
  </xs:simpleType>
  <!--END SIMPLE TYPES-->
  
  <!--COMPLEX TYPES-->
  <xs:complexType name="resourceConfigsType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="ResourceConfig" type="validPath" />
    </xs:choice>
  </xs:complexType>
  
  <!--This defines the allowed content in the "GlobalConfig" element.-->
  <xs:complexType name="globalConfigType">
    <xs:all>
      <xs:element name="BespokeServerHostname" type="xs:normalizedString"/>
      <xs:element name="ConfigPath" type="validPath"/>
      <xs:element name="TestRunPath" type="validPath"/>
      <xs:element name="TestPlanPath" type="validPath"/>
      <xs:element name="TestScriptPath" type="validPath"/>
      <xs:element name="ToolPath" type="validPath"/>
      <xs:element name="ResultsPath" type="validPath"/>
      <xs:element name="ResultsURL" type="xs:normalizedString"/>
      <xs:element name="GlobalLog" type="validPath"/>
      <xs:element name="ResourceConfigs" type="resourceConfigsType"/>
    </xs:all>
    <xs:attribute name="version" type="xs:positiveInteger" use="required" />
  </xs:complexType>
  <!--END COMPLEX TYPES-->
  
  <!--ELEMENTS-->
  <!--This is the main element in the XML config file.-->
  <xs:element name="GlobalConfig" type="globalConfigType"/>
  <!--END ELEMENTS-->
</xs:schema>

=== UnitasBrooks/bespoke/src/bespoke/configs/GlobalConfig_v3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- This config contains settings for Bespoke used for all test runs or contains default settings -->
<GlobalConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd\global_config.xsd" version="3">
  
  <!-- Required -->
  <!-- Warning! If not set correctly Bespoke will fail to run. -->
  <BespokeServerHostname>Grim</BespokeServerHostname>
  
  <!-- These paths are all absolute on the Bespoke server -->
  <ConfigPath>/home/meowzilla/bespoke/configs</ConfigPath>
  <TestRunPath>/home/meowzilla/meowcorp/testruns</TestRunPath>
  <TestPlanPath>/home/meowzilla/meowcorp/meowmeowcom/testplans</TestPlanPath>
  <TestScriptPath>/home/meowzilla/meowcorp/meowmeowcom/testscripts</TestScriptPath>
  <ToolPath>/home/meowzilla/meowcorp/gitrepo/tools</ToolPath>
  <ResultsPath>/home/meowzilla/meowcorp/girrepo/results</ResultsPath>
  
  <!-- UNC Path for TestManager controller resources (Needed for results) -->
  <ResultsURL>\\ryan-pc.bespoke.com\bespoke</ResultsURL>

  <!-- Global Log -->
  <!-- This log will eventually be copied into the results directory -->
  <GlobalLog>bespoke_trace.log</GlobalLog>
  
  <!-- These paths are all relative to the ConfigPath above -->
  <!-- Default Resource Configs -->
  <ResourceConfigs>
    <ResourceConfig>ResourceConfig.xml</ResourceConfig>
  </ResourceConfigs>
  <!-- END REQUIRED -->
  
</GlobalConfig>
