=== UnitasBrooks/bespoke/src/bespoke/xsd/test_plan.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!--SIMPLE TYPES-->
  <!--The path can be followed by a backslash.-->
  <xs:simpleType name="validPath">
    <xs:restriction base="xs:normalizedString">
      <xs:minLength value="1"/>
      <xs:maxLength value="260"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:normalizedString">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="resourceTypeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="system" />
    </xs:restriction>
  </xs:simpleType>
  <!--END SIMPLE TYPES-->
  
  <!--COMPLEX TYPES-->
  <xs:complexType name="dictionaryType">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attribute name="name" type="xs:normalizedString" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="restartComputerType">
    <xs:simpleContent>
      <xs:extension base="xs:boolean">
        <xs:attribute name="wait" type="xs:boolean" use="optional" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="toolsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Tool" type="xs:normalizedString"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="buildsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Build" type="xs:normalizedString"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="paramsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Param" type="dictionaryType"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="prepareVirtualMachineType">
    <xs:all>
      <xs:element name="VirtualMachine" type="xs:normalizedString" />
      <xs:element name="Checkpoint" type="xs:normalizedString" />
      <xs:element name="Tools" type="toolsType" />
      <xs:element name="Builds" type="buildsType" />
      <xs:element name="PostWait" type="xs:positiveInteger" />
      <xs:element name="TimeOut" type="xs:positiveInteger" />
      <xs:element name="RestartComputer" type="restartComputerType" />
    </xs:all>
    <xs:attribute name="resource_id" type="xs:normalizedString" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="resourceInitType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="PrepareVirtualMachine" type="prepareVirtualMachineType"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="stepType">
    <xs:all>
      <xs:element name="Description" type="nonEmptyString" />
      <xs:element name="ResourceID" type="nonEmptyString" />
      <xs:element name="Directory" type="validPath" />
      <xs:element name="Interpreter" type="xs:normalizedString" />
      <xs:element name="Executable" type="nonEmptyString" />
      <xs:element name="ExecParams" type="paramsType" />
      <xs:element name="PostWait" type="xs:positiveInteger" />
      <xs:element name="TimeOut" type="xs:positiveInteger" />
      <xs:element name="RestartComputer" type="restartComputerType" />
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="refreshResourceType">
    <xs:all>
      <xs:element name="ResourceID" type="xs:normalizedString" />
      <xs:element name="RestartComputer" type="restartComputerType" />
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="testStepsType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Step" type="stepType"/>
      <xs:element name="RefreshResource" type="refreshResourceType"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="testCaseType">
    <xs:all>
      <xs:element name="ResourceInit" type="resourceInitType" />
      <xs:element name="TestSteps" type="testStepsType" />
    </xs:all>
    <xs:attribute name="name" type="xs:normalizedString" use="required"/>
  </xs:complexType>
  
  <!--This defines the allowed content in the "VMConfig" element.-->
  <xs:complexType name="testPlanType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="TestCase" type="testCaseType" />
    </xs:choice>
    <xs:attribute name="name" type="xs:normalizedString" use="required" />
    <xs:attribute name="version" type="xs:positiveInteger" use="required" />
  </xs:complexType>
  <!--END COMPLEX TYPES-->
  
  <!--ELEMENTS-->
  <!--This is the main element in the XML config file.-->
  <xs:element name="TestPlan" type="testPlanType" />
  <!--END ELEMENTS-->
</xs:schema>

=== UnitasBrooks/bespoke/src/bespoke/configs/TestPlan_V3.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestPlan name="Compiler_Test_Plan" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\xsd\test_plan.xsd" version="3">
  
  <!--Start Test Case-->
  <TestCase name="Windows_2008_x64_Test">
    <ResourceInit>
      <PrepareVirtualMachine resource_id="Test_System">
        <VirtualMachine>Win-2k8-R2-64</VirtualMachine>
        <Checkpoint>ReadyToAutoTest</Checkpoint>
        <Tools>
          <Tool>Python_2.7</Tool>
          <Tool>FL_Python_Lib</Tool>
        </Tools>
        <Builds>
          <Build>Fancy_Lads_Compiler_2.0</Build>
        </Builds>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">true</RestartComputer>
      </PrepareVirtualMachine>
    </ResourceInit>
    <TestSteps>
      <Step>
        <Description>Valid Compiler Test Step</Description>
        <ResourceID>Test_System</ResourceID>
        <Directory>Fancy_Lads\Compiler_Tests</Directory>
        <Interpreter></Interpreter>
        <Executable>Compiler_Valid.exe</Executable>
        <!--All Bespoke environment variables should begin with BS otherwise system env is used -->
        <ExecParams>
          <Param name="--resultsPath">%BS|RESULTSPATH%</Param>
          <Param name="--cwd">%BS|CWD%</Param>
          <Param name="--hostname">%BS|Test_System%</Param>
        </ExecParams>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">false</RestartComputer>
      </Step>
      
      <RefreshResource>
        <ResourceID>Test_System</ResourceID>
        <RestartComputer wait="true">true</RestartComputer>
      </RefreshResource>
      
      <Step>
        <Description>Invalid Compiler Test Step</Description>
        <ResourceID>Test_System</ResourceID>
        <Directory>Fancy_Lads\Compiler_Tests</Directory>
        <Interpreter></Interpreter>
        <Executable>Compiler_Invalid.exe</Executable>
        <!--All environment variables should begin with BS for Bespoke otherwise system env is used -->
        <ExecParams>
          <Param name="--resultsPath">%BS|RESULTSPATH%</Param>
          <Param name="--cwd">%BS|CWD%</Param>
          <Param name="--hostname">%BS|Test_System%</Param>
        </ExecParams>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">false</RestartComputer>
      </Step>
    </TestSteps>
  </TestCase>
  <!--End Test Case-->
  
  <!--Start Test Case-->
  <TestCase name="Windows_7_x64_Test">
    <ResourceInit>
      <PrepareVirtualMachine resource_id="Server1">
        <VirtualMachine>WIN-7-64</VirtualMachine>
        <Checkpoint>ReadyToAutoTest</Checkpoint>
        <Tools>
          <Tool>Python_2.7</Tool>
          <Tool>FL_Python_Lib</Tool>
        </Tools>
        <Builds>
          <Build>Fancy_Lads_Compiler_2.0</Build>
        </Builds>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">true</RestartComputer>
      </PrepareVirtualMachine>
    </ResourceInit>
    <TestSteps>
      <Step>
        <Description>Valid Compiler Test Step</Description>
        <ResourceID>Server1</ResourceID>
        <Directory>Fancy_Lads\Compiler_Tests</Directory>
        <Interpreter></Interpreter>
        <Executable>Compiler_Valid.exe</Executable>
        <!--All environment variables should begin with BESPOKE otherwise system env is used -->
        <ExecParams>
          <Param name="--resultsPath">%BS|RESULTSPATH%</Param>
          <Param name="--cwd">%BS|CWD%</Param>
          <Param name="--hostname">%BS|Test_System%</Param>
        </ExecParams>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">false</RestartComputer>
      </Step>
      
      <RefreshResource>
        <ResourceID>Server1</ResourceID>
        <RestartComputer wait="true">true</RestartComputer>
      </RefreshResource>
      
      <Step>
        <Description>Invalid Compiler Test Step</Description>
        <ResourceID>Server1</ResourceID>
        <Directory>Fancy_Lads\Compiler_Tests</Directory>
        <Interpreter></Interpreter>
        <Executable>Compiler_Invalid.exe</Executable>
        <!--All environment variables should begin with BS for Bespoke otherwise system env is used -->
        <ExecParams>
          <Param name="--resultsPath">%BS|RESULTSPATH%</Param>
          <Param name="--cwd">%BS|CWD%</Param>
          <Param name="--hostname">%BS|Test_System%</Param>
        </ExecParams>
        <PostWait>5</PostWait>
        <TimeOut>600</TimeOut>
        <RestartComputer wait="true">false</RestartComputer>
      </Step>
    </TestSteps>
  </TestCase>
  <!--End Test Case-->
  
</TestPlan>
